events {}

http {

    server {
        listen 80;

        # ingestion-service
        location /logs {
            proxy_pass http://ingestion-service:5000/logs;
        }

        # search-service
        location /search {
            proxy_pass http://search-service:5001/logs;
        }
    }
}